# Generated by Django 5.0.6 on 2024-06-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelName', models.CharField(max_length=256)),
                ('writtenExam', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('publishDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('joinDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollmentDate', models.DateField(auto_now_add=True)),
                ('progress', models.IntegerField()),
                ('status', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uol.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uol.user')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('ReviewDate', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uol.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uol.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Uol.user'),
        ),
    ]
